config/routes.rb
Rails.application.routes.draw do
  resources :genres

  resources :users

  get 'signup' => 'users#new'

  root "movies#index"

  resources :movies do
    resources :reviews
    resources :favorites
  end

  resource :session

  get "sign_in" => "sessions#new"
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :characterizations, dependent: :destroy
  has_many :movies, through: :characterizations
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :require_signin, except: [:index, :show]
  before_action :require_admin, except: [:index, :show]

  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
    @movies = @genre.movies
  end

  def new
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to @genre, notice: "Genre successfully created!"
    else
      render :new
    end
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to @genre, notice: "Genre successfully updated!"
    else
      render :new
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to genres_url, alert: "Genre successfully deleted!"
  end

private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_for(@genre) do |f| %>
  <%= render "shared/errors", object: @genre %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true %>
      </li>
    </ol>
    <p>
      <%= f.submit %>
      <%= link_to "Cancel", genres_path, class: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/genres/edit.html.erb
<header id="content-header">
  <h1>Edit a Genre</h1>
</header>

<%= render "form" %>

app/views/genres/index.html.erb
<h3> Genres </h3>
<ul id="genres">
  <% @genres.each do |genre| %>
    <li>
      <%= link_to genre.name, genre_path(genre) %>
    </li>
  <% end %>
</ul>

app/views/genres/new.html.erb
<header id="content-header">
  <h1>Create a New Genre</h1>
</header>

<%= render "form" %>

app/views/genres/show.html.erb
<h3> Movies in the <%= @genre.name %> Genre </h3>

  <% @genre.movies.each do |movie| %>
    <%= link_to movie.title, movie %>
  <% end %>

  <footer>
    <nav>
      <% if current_user_admin? %>
        <%= link_to 'Edit', edit_genre_path(@genre), class: 'button' %>
        <%= link_to 'Delete', @genre,
                    class: 'button',
                    method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </nav>
  </footer>