config/routes.rb
Rails.application.routes.draw do
  resources :genres

  resources :users

  get 'signup' => 'users#new'

  root "movies#index"

  resources :movies do
    resources :reviews
    resources :favorites
  end

  resource :session

  get "sign_in" => "sessions#new"
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
    Copyright &copy; 2015
    <%= link_to 'The Pragmatic Studio', 'http://pragmaticstudio.com' %>
  </p>
  <p>
    For educational purposes only.
  </p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
  <div id="masthead">
    <h1><%= link_to 'Flix', root_path %></h1>
    <nav>
      <p>
        <% if current_user %>
          <%= link_to current_user.name, current_user, class: "button" %>
          <%= link_to "Account Settings", edit_user_path(current_user), class: "button" %>
          <%= link_to "Sign Out", session_path, method: :delete, class: "button" %>
        <% else %>
          <%= link_to "Sign Up", signup_path, class: "button" %>
          <%= link_to "Sign In", sign_in_path, class: "button" %>
        <% end %>
      </p>
    </nav>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <% if current_user_admin? %>
      <ul>
        <li class="all-movies">
          <%= link_to 'All Movies', movies_path, class: 'button' %>
        </li>
        <li class="create-movie">
          <%= link_to 'Add New Movie', new_movie_path, class: 'button' %>
        </li>
        <li class="all-genres">
          <%= link_to 'All Genres', genres_path, class: 'button' %>
        </li>
        <li class="create-genre">
          <%= link_to 'Add New Genre', new_genre_path, class: 'button' %>
        </li>
      </ul>
    <% end %>
  </nav>
  <%= content_for :side %>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= page_title %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>

<div id="wrapper">

  <%= render "layouts/flashes" %>

  <div id="container">
    <section id="sidebar">
      <%= render "layouts/sidebar" %>
    </section>
    <section id="content">
      <%= yield %>
    </section>
  </div>

</div>

<%= render "layouts/footer" %>

</body>
</html>